# install.packages(c("raster","sp","rgdal","rgeos","plyr"))

##### Loading Required Packages #####

library(raster)
library(sp)
library(rgdal)
library(rgeos)
library(plyr)

##### Reading in Vector Data #####

#read in shapefiles
#readOGR in rgdal does this
g1966 <- readOGR("~/Documents/GitHub/GEOG331/Activity 6/a06/GNPglaciers/GNPglaciers_1966.shp")

g1998 <- readOGR("~/Documents/GitHub/GEOG331/Activity 6/a06/GNPglaciers/GNPglaciers_1998.shp")

g2005 <- readOGR("~/Documents/GitHub/GEOG331/Activity 6/a06/GNPglaciers/GNPglaciers_2005.shp")

g2015 <- readOGR("~/Documents/GitHub/GEOG331/Activity 6/a06/GNPglaciers/GNPglaciers_2015.shp")


str(g2015) # investigate format of g2015 data
           # Note there are 39 glaciers for each .shp file and a table with information about
           # each glacier that has 13 columns of data

#data stores all accompanying info/measurements for each spatial object
head(g2015@data)

#polygons stores the coordinates for drawing the polygons
g2015@polygons[[1]]

##### Question 1 #####

g1966@proj4string #Projection info for the vector object describing glacier outlines in 1966 (g1966)

##### Glacier names in 2015 don’t match the rest of the shapefiles: FIXED below  #####

#fix glacier name so that it is consistent with the entire time period
g2015@data$GLACNAME <- ifelse(g2015@data$GLACNAME == "North Swiftcurrent Glacier",
                              "N. Swiftcurrent Glacier",
                              ifelse(   g2015@data$GLACNAME ==  "Miche Wabun", 
                                        "Miche Wabun Glacier",
                                        as.character(g2015@data$GLACNAME)))

##### Mapping satellite imagery: Loading and processing raster data #####

#read in rgb imagery from landsat
redL <- raster("~/Documents/GitHub/GEOG331/Activity 6/a06/glacier_09_05_14/l08_red.tif")
greenL <- raster("~/Documents/GitHub/GEOG331/Activity 6/a06/glacier_09_05_14/l08_green.tif")
blueL <- raster("~/Documents/GitHub/GEOG331/Activity 6/a06/glacier_09_05_14/l08_blue.tif")

#make a brick that stacks all layers
rgbL <- brick(redL, greenL, blueL)

#Subset the plot below to zoom in on closer on a few glaciers
plotRGB(rgbL, ext=c(289995,310000,5371253,5400000), stretch="lin")
plot(g1966, col="palegreen2", border=NA, add=TRUE)
plot(g1998, col="royalblue3", add=TRUE, border=NA)
plot(g2005, col="darkgoldenrod4", add=TRUE, border=NA)
plot(g2015, col="tomato3", add=TRUE, border=NA)

##### Working with raster data #####

## Note on raster data: Each item in list below represents one year of raster data
## NDVI data is the maximum NDVI that is observed for each year and is a derived 
## data product generated by the USGS eModis Phenology program

#set up years to read in
ndviYear <- seq(2003,2016)

#read all files into a list
NDVIraster <- list() 
for(i in 1:length(ndviYear)){
  NDVIraster[[i]] <- raster(paste0("~/Documents/GitHub/GEOG331/Activity 6/a06/NDVI/NDVI_",ndviYear[i],".tif"))
  
}

##### Answer 2 #####

#get projection
NDVIraster[[1]]@crs

## Answer 3 ##

plot(g1966, col="black", axes=T) # Plot of 1966 glacier data separately

par(mai=c(1,1,1,1))
plot(g1966, col="black", axes=T)
plot(NDVIraster[[1]], add=T, border=NA)

dev.off()
par(mai=c(0.5,0.5,0.5,0.5))
par(mfrow= c(1,2))
plot(NDVIraster[[1]], axes=T)
plot(g1966, col="black", axes=T)

##### Vector data analysis: Glacier retreat #####

#reproject the glaciers
#use the NDVI projection
#spTransform(file to project, new coordinate system)
g1966p <- spTransform(g1966,NDVIraster[[1]]@crs)
g1998p <- spTransform(g1998,NDVIraster[[1]]@crs)
g2005p <- spTransform(g2005,NDVIraster[[1]]@crs)
g2015p <- spTransform(g2015,NDVIraster[[1]]@crs)

##### Answer 4 #####

dev.off()
par(mai=c(0.3,0.3,0.3,0.3))
plot(NDVIraster[[13]], axes=F)
#add polygons to plot
plot(g2015p, border="black", add=TRUE, axes=F)

##### Analyzing areas of glaciers throughout each year #####

#calculate area for all polygons
#add directly into data table for each shapefile
g1966p@data$a1966m.sq <- area(g1966p)
g1998p@data$a1998m.sq <- area(g1998p)
g2005p@data$a2005m.sq <- area(g2005p)
g2015p@data$a2015m.sq <- area(g2015p)

gAllp1 <- join(g1966p@data,g1998p@data, by="GLACNAME", type="full")
gAllp2 <- join(gAllp1,g2005p@data, by="GLACNAME", type="full")
gAll <- join(gAllp2,g2015p@data, by="GLACNAME", type="full")

##### Answer 5 #####

for(i in 1:39){
  # Calculate percentage change in area between 1996 and 2015
  # abs(((area2015-area1996)/area1996)*100))
  gAll$a2015per.change[i]<- (abs(area(g2015p)[i]-area(g1966p)[i])/area(g1966p)[i])*100
  
  # add percentage change in area as a column to the g2015p glacier vector data
  g2015p@data$a2015per.change[i]<- (abs(area(g2015p)[i]-area(g1966p)[i])/area(g1966p)[i])*100
}

# Make a spplot of the glaciers in 2015 showing the % change each glacier has experienced
spplot(g2015p, "a2015per.change")

##### Answer 6 #####

# Finding the glacier with the largest % loss
maxloss_glac<- gAll$GLACNAME[gAll$a2015per.change==max(gAll$a2015per.change)] 

#Without background imagery (with axes)
plot(subset(g1966, g1966@data$GLACNAME=="Boulder Glacier"), col="palegreen2", border=NA, axes=T)
plot(subset(g1998, g1998@data$GLACNAME=="Boulder Glacier"), col="royalblue3", add=TRUE, border=NA)
plot(subset(g2005, g2005@data$GLACNAME=="Boulder Glacier"), col="darkgoldenrod4", add=TRUE, border=NA)
plot(subset(g2015, g2015@data$GLACNAME=="Boulder Glacier"), col="tomato3", add=TRUE, border=NA)

#Alternative 1
plotRGB(rgbL, ext=c(272500,275500,5425100,5432600), stretch="lin")
plot(subset(g1966, g1966@data$GLACNAME=="Boulder Glacier"), col="palegreen2", border=NA, add=T)
plot(subset(g1998, g1998@data$GLACNAME=="Boulder Glacier"), col="royalblue3", add=TRUE, border=NA)
plot(subset(g2005, g2005@data$GLACNAME=="Boulder Glacier"), col="darkgoldenrod4", add=TRUE, border=NA)
plot(subset(g2015, g2015@data$GLACNAME=="Boulder Glacier"), col="tomato3", add=TRUE, border=NA)

#Alternative 2
plotRGB(rgbL, ext=c(271000,279600,5420000,5431000), stretch="lin", main="Glacier extent for all years 
        for Boulder Glacier that has experienced 84.721% loss in area between 1966 and 2015")
plot(subset(g1966, g1966@data$GLACNAME=="Boulder Glacier"), col="palegreen2", border=NA, add=T,
     main= "Glacier extent for all years 
        for Boulder Glacier that has experienced 84.721% loss in area between 1966 and 2015")
plot(subset(g1998, g1998@data$GLACNAME=="Boulder Glacier"), col="royalblue3", add=TRUE, border=NA)
plot(subset(g2005, g2005@data$GLACNAME=="Boulder Glacier"), col="darkgoldenrod4", add=TRUE, border=NA)
plot(subset(g2015, g2015@data$GLACNAME=="Boulder Glacier"), col="tomato3", add=TRUE, border=NA)

##### Question 7 #####

#designate that NDVIraster list is a stack
NDVIstack <- stack(NDVIraster)
#set up lm function to apply to every cell
#where x is the value of a cell
#need to first skip NA values (like lakes)
#if NA is missing in first raster, it is missing in all
#so we can tell R to assign an NA rather than fitting the function
timeT <- ndviYear
fun <- function(x) {
  if(is.na(x[1])){
    NA}else{
      #fit a regression and extract a slope
      lm(x ~ timeT)$coefficients[2] }}
#apply the slope function to the rasters
NDVIfit <- calc(NDVIstack,fun)
#plot the change in NDVI
plot(NDVIfit, axes=FALSE)

##### Creating and analyzing buffer glaciers #####

#buffer glaciers
glacier500m <- gBuffer(g1966p,#data to buffer
                       byid=TRUE,#keeps original shape id 
                       width=500)#width in coordinate system units
#convert to a raster
par(mai=c(0.4,0.4,0.4,0.4))
buffRaster <- rasterize(glacier500m,#vector to convert to raster
                        NDVIraster[[1]], #raster to match cells and extent
                        field=glacier500m@data$GLACNAME, #field to convert to raster data
                        background=0)#background value for missing data
plot(buffRaster)

##### Question 8 #####

#rasterize gralciers
glacRaster <- rasterize(g1966p, NDVIraster[[1]], field=g1966p@data$GLACNAME, background=0)
#subtract buffer from original glacier
glacZones <- buffRaster - glacRaster
plot(glacZones)


##### Question 9 #####

#mean change in NDVI per year
meanChange <- zonal(NDVIfit, #NDVI function to summarize
                    glacZones,#raster with zones
                    "mean")#function to apply

#remove zone zero from mean change in NDVI per year
meanChange<-meanChange[-1,]

# add mean change in NDVI per year into the 2015 glacier polygons
g2015@data$meanChange<-meanChange[,2]

# map where the mean change in vegetation is color coded within the 2015 glacier polygons
spplot(g2015, "meanChange")

##### Question 10 #####

range_NDVI<-range(meanChange[,2]) # range of mean change in NDVI values
# Range: [-0.0012, 0.004]

# proportion of values in meanChange which are positive
prop_pos_NDVI<- length(subset(meanChange[,2], meanChange[,2]>0))/39 # 74%

##### Question 11 #####

# raster dataset representing the average maximum NDVI change across
# all years within Glacier National Park

NDVIfit_avg <- calc(NDVIstack,mean) 

meanChange <- zonal(NDVIfit_avg, #NDVI function to summarize
                    glacZones,#raster with zones
                    "mean")#function to apply
meanChange<-meanChange[-1,] # removing zone zero

for(i in 1:39){
  # add average maximum NDVI across each year as a column to the g2015p glacier vector data
  g2015p@data$NDVImean[i]<- meanChange[i,2]
}


plot(NDVIfit_avg, axes=F, legend= T, main="Glacier extent by surrounding\nmaximum NDVI average")
g2015p@data$NDVIcol <- ifelse(g2015p@data$NDVImean<0.2,"blue",
                        ifelse(g2015p@data$NDVImean<0.3, "darkorchid1",
                        ifelse(g2015p@data$NDVImean<0.4, "gray48",
                        ifelse(g2015p@data$NDVImean<0.5, "gray0", 
                        ifelse(g2015p@data$NDVImean<0.6, "deeppink", "firebrick1")))))
legend("topleft", c("<0.2","<0.3","<0.4", 
        "<0.5", "<0.6", ">=0.6"), fill=c("blue", "darkorchid1", "gray48", "gray0",
                                         "deeppink", "firebrick1" ), horiz=FALSE, cex=0.8)
plot(g2015p, add=TRUE, col=paste(g2015p@data$NDVIcol),border=FALSE)